### ISSUE TITLE
Error of make install on mac terminal with zsh

### ISSUE THREAD

**Issue by keitheis** [c9s/hypergit.vim#2]
On os x 10.6 terminal and zsh, I git clone to ~/PlaySquare/Vim/hypergit.vim and cd there and make install and got error:
 
% make install
/Users/keitheis/.vim/record
find: \033[33mafter\033[m\033[m: No such file or directory
find: \033[33mautoload\033[m\033[m: No such file or directory
find: \033[33mdoc\033[m\033[m: No such file or directory
find: \033[33mplugin\033[m\033[m: No such file or directory
find: \033[33msyntax\033[m\033[m: No such file or directory
mkdir -p plugin
 => plugin/treemenu.vim
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13358  100 13358    0     0  13324      0  0:00:01  0:00:01 --:--:-- 18501
 => plugin/helper.vim
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1510  100  1510    0     0   2370      0 --:--:-- --:--:-- --:--:--  4217
Installing
find: \033[33mafter\033[m\033[m: No such file or directory
find: \033[33mautoload\033[m\033[m: No such file or directory
find: \033[33mdoc\033[m\033[m: No such file or directory
find: \033[33mplugin\033[m\033[m: No such file or directory
find: \033[33msyntax\033[m\033[m: No such file or directory
find: \033[33mafter\033[m\033[m: No such file or directory
find: \033[33mautoload\033[m\033[m: No such file or directory
find: \033[33mdoc\033[m\033[m: No such file or directory
find: \033[33mplugin\033[m\033[m: No such file or directory
find: \033[33msyntax\033[m\033[m: No such file or directory
vim --noplugin -V10install.log -c "so .mkrecord" -c "q"
make: *** [record] Error 1

**Comment by c9s** [comment]
please feel free to reopen this if it still occurs
