### ISSUE TITLE
Error in Vim 7.4.273

### ISSUE THREAD

**Issue by walkingice** [c9s/hypergit.vim#3]
When I upgrade vim along with system upgrade, vim complains to me whenever I try to edit any file.

>處理 /home/walkingice/.vim/bundle/hypergit.vim/plugin/hypergit-util.vim 時發生錯誤:
>行  101:
>E128: Function name must start with a capital or "s:": g:gitSkipCommit()
>行  105:
>E193: :endfunction 必須在函式內部使用
>行  107:
>E128: Function name must start with a capital or "s:": g:gitDoCommit()
>Skipped
>行  111:
>E133: :return 必須在函式裡使用
>Committing...
>行  128:
>E121: 變數 g:git_bin 尚未定義
>E116: 函式 printf('%s commit --cleanup=strip -a -F %s', g:git_bin , file ) 的引數不正確
>E15: 不正確的運算式: printf('%s commit --cleanup=strip -a -F %s', g:git_bin , file )
>Done
>行  137:
>E193: :endfunction 必須在函式內部使用
>Press ENTER or type command to continue

I have no idea how to fix it, just give a shot and vim does not complain anymore.

    diff --git a/plugin/hypergit-util.vim b/plugin/hypergit-util.vim
    index 2c1140f..24f4673 100644
    --- a/plugin/hypergit-util.vim
    +++ b/plugin/hypergit-util.vim
    @@ -98,13 +98,13 @@ fun! s:filterMessage(msgfile)
     endf
     
     
    -fun! g:gitSkipCommit()
    +fun! s:gitSkipCommit()
       let file = expand('%')
       cal delete(file)
       bw!
     endf
     
    -fun! g:gitDoCommit()
    +fun! s:gitDoCommit()
       let file = expand('%')
       if ! filereadable(file) 
         echo "Skipped"
    -- 
    2.0.0.rc0

**Comment by c9s** [comment]
please reopen if it still occur
